global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
  secretName: "employee-system-4/dev/db-credentials"

grafana:
  service:
    name: prometheus-grafana
    port: 80

client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: "4e237f1109ca06302c7fa9e39a073a77095562c8"
  service:
    name: "employee-system-employee-app-frontend"
    type: NodePort
    port: 80
  replicaCount: 1

server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: "4e237f1109ca06302c7fa9e39a073a77095562c8"
  service:
    name: "employee-system-employee-app-backend"
    type: NodePort
    port: 3001
  replicaCount: 1