global:
  imagePullPolicy: IfNotPresent

client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: "latest"
  service:
    type: clusterIP
    port: 80

server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: "latest"
  service:
    type: clusterIP
    port: 3001
  env:
    MYSQL_HOST: #rds-endpoint
    MYSQL_PORT: 3306
    MYSQL_USER: secret
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: employeeSystemDB