apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/orikerbis/application-repo.git"
    targetRevision: main
    path: employee-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: employee-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
