version: "3.8"
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Host port 3000 -> Container port 80 (Nginx)
    depends_on:
      - backend

  backend: 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Host port 5000 -> Container port 5000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: employeeSystem

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: employeeSystem
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
volumes:
  db_data:
  