CREATE DATABASE IF NOT EXISTS `employee-db`;

USE `employee-db`;

CREATE TABLE IF NOT EXISTS `employees` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `wage` DECIMAL(10, 2) NOT NULL
);