apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-app.fullname" . }}-client
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
  namespace: employee-system
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "employee-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-client
          image: "825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend:2bc3214447be56cb512483b1a670019c39578fd6"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.client.service.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.client.service.port }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10