apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: employee-system-db
  namespace: employee-system  
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: employee-system-db
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: rds-db-credentials
        
   