apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-system-ingress-backend
  namespace: employee-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: api.kerbis.online
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.server.service.name }}
            port: 
              number: {{ .Values.server.service.port }}
