apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-system-ingress-frontend
  namespace: employee-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: app.kerbis.online
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.client.service.name }}
            port:
              number: {{ .Values.client.service.port }}