apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-app.fullname" . }}-backend
  namespace: employee-system
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      protocol: TCP
  selector:
    {{- include "employee-app.selectorLabels" . | nindent 4 }}
