apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-app.fullname" . }}-frontend
  namespace: employee-system
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "employee-app.selectorLabels" . | nindent 4 }}
