apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "employee-app.labels" . | nindent 6 }}
      app: frontend
  namespaceSelector:
    matchNames:
      - employee-system
  endpoints:
    - port: http
      interval: 15s