apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      {{- include "employee-app.labels" . | nindent 6 }}
      app: frontend 
  endpoints:
    - port: http
      interval: 30s