apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-chart.fullname" . }}-client
  labels:
    app: {{ include "your-chart.name" . }}-client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "your-chart.name" . }}-client