apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "your-chart.fullname" . }}-client
  labels:
    app: {{ include "your-chart.name" . }}-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "your-chart.name" . }}-client
  template:
    metadata:
      labels:
        app: {{ include "your-chart.name" . }}-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.client.service.port }}
         