apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-chart.fullname" . }}-server
  labels:
    app: {{ include "your-chart.name" . }}-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "your-chart.name" . }}-server